# Generated by Django 2.1.1 on 2018-09-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='faceEncode',
            field=models.CharField(max_length=3000),
        ),
    ]
