# Generated by Django 2.1.1 on 2018-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0003_auto_20180908_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='faceEncode',
            field=models.FileField(upload_to='encodes/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='facePicture',
            field=models.FileField(upload_to='faces/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastLoginPicture',
            field=models.FileField(upload_to='lastPhoto/'),
        ),
    ]
