# Generated by Django 2.1.1 on 2018-09-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0004_auto_20180908_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='faceEncode',
            field=models.CharField(max_length=200),
        ),
    ]
