# Generated by Django 2.1.1 on 2018-09-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0005_auto_20180909_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='faceEncode',
            field=models.FileField(upload_to='encodes/'),
        ),
    ]
