# Generated by Django 2.1.2 on 2018-10-02 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0007_person_associateduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='associatedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
